<?php
/**
 * Copyright (c) 2024 Attila Sagi
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/**
 * @var $block \Space\WishlistAdminEmail\Block\Wishlist\WishlistItems
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<table class="email-items">
    <thead>
    <tr>
        <th class="item-info"></th>
        <th class="item-info">
            <strong><?= $escaper->escapeHtml(__('Product Name')) ?></strong>
        </th>
        <th class="item-price">
            <strong><?= $escaper->escapeHtml(__('Price')) ?></strong>
        </th>
        <th class="item-qty">
            <strong><?= $escaper->escapeHtml(__('Qty')) ?></strong>
        </th>
        <th class="item-info"></th>
    </tr>
    </thead>
    <?php if ($block->getShowAllItems()): ?>
        <?php $currentItem = $block->getItem(); ?>
        <?php $items = $block->getWishlistItems(); ?>
        <?php if ($items): ?>
            <tbody>
            <?php foreach ($items as $item): ?>
                <?php $product = $block->getProduct($item); ?>
                <tr>
                    <td class="item-info">
                        <a href="<?= $escaper->escapeUrl($item->getProductUrl()) ?>">
                            <img src="<?= $escaper->escapeUrl($block->getImage($product)) ?>"
                                 alt="<?= $escaper->escapeHtml($product->getName()) ?>" />
                        </a>
                    </td>
                    <td class="item-info">
                        <a href="<?= $escaper->escapeUrl($item->getProductUrl()) ?>">
                            <p class="product-name"><?= $escaper->escapeHtml($product->getName()) ?></p>
                        </a>
                        <p class="sku">
                            <?= $escaper->escapeHtml(__('Sku')) ?>: <?= $escaper->escapeHtml($product->getSku()) ?>
                        </p>
                        <?php if ($currentItem->getId() === $item->getId()): ?>
                            <p class="new" style="color: red;">
                                <?= $escaper->escapeHtml(__('Just Added')) ?>
                            </p>
                        <?php endif; ?>
                        <?php if ($item->getDescription()): ?>
                            <p class="description">
                                <?= $escaper->escapeHtml(__('Comment')) ?>:<br />
                                <?= $escaper->escapeHtml($item->getDescription()) ?>
                            </p>
                        <?php endif; ?>
                    </td>
                    <td class="item-price">
                        <?= $block->getProductPriceHtml($product) ?>
                    </td>
                    <td class="item-qty">
                        <?= $escaper->escapeHtml((int)$item->getQty()) ?>
                    </td>
                    <td class="item-info">
                        <a href="<?= $escaper->escapeUrl($item->getProductUrl()) ?>"
                           title="<?= $escaper->escapeHtml($product->getName()) ?>">
                            <?= $escaper->escapeHtml(__('View Product')) ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        <?php else: ?>
            <tbody>
                <tr>
                    <td class="item-info" colspan="5">
                        <p><?= $escaper->escapeHtml(__('Wishlist items not found.')) ?></p>
                    </td>
                </tr>
            </tbody>
        <?php endif; ?>
    <?php else: ?>
        <?php $item = $block->getItem(); ?>
        <?php if (null !== $item): ?>
            <?php $product = $block->getProduct($item); ?>
            <tbody>
                <tr>
                    <td class="item-info">
                        <a href="<?= $escaper->escapeUrl($item->getProductUrl()) ?>">
                            <img src="<?= $escaper->escapeUrl($block->getImage($product)) ?>"
                                 alt="<?= $escaper->escapeHtml($product->getName()) ?>" />
                        </a>
                    </td>
                    <td class="item-info">
                        <a href="<?= $escaper->escapeUrl($item->getProductUrl()) ?>">
                            <p class="product-name"><?= $escaper->escapeHtml($product->getName()) ?></p>
                        </a>
                        <p class="sku">
                            <?= $escaper->escapeHtml(__('Sku')) ?>: <?= $escaper->escapeHtml($product->getSku()) ?>
                        </p>
                        <p class="new" style="color: red;">
                            <?= $escaper->escapeHtml(__('Just Added')) ?>
                        </p>
                        <?php if ($item->getDescription()): ?>
                            <p class="description">
                                <?= $escaper->escapeHtml(__('Comment')) ?>:<br />
                                <?= $escaper->escapeHtml($item->getDescription()) ?>
                            </p>
                        <?php endif; ?>
                    </td>
                    <td class="item-price">
                        <?= $block->getProductPriceHtml($product) ?>
                    </td>
                    <td class="item-qty">
                        <?= $escaper->escapeHtml($item->getQty()) ?>
                    </td>
                    <td class="item-info">
                        <a href="<?= $escaper->escapeUrl($item->getProductUrl()) ?>"
                           title="<?= $escaper->escapeHtml($product->getName()) ?>">
                            <?= $escaper->escapeHtml(__('View Product')) ?>
                        </a>
                    </td>
                </tr>
            </tbody>
        <?php else: ?>
            <tbody>
                <tr>
                    <td class="item-info" colspan="5">
                        <p><?= $escaper->escapeHtml(__('Wishlist item not found.')) ?></p>
                    </td>
                </tr>
            </tbody>
        <?php endif; ?>
    <?php endif; ?>
</table>
