<?php
/**
 * Copyright (c) 2024 Attila Sagi
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/**
 * @var $block \Space\WishlistAdminEmail\Block\Wishlist\WishlistItems
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<table class="email-items">
    <thead>
    <tr>
        <th class="item-info">
            <?= $escaper->escapeHtml(__('Items')) ?>
        </th>
        <th class="item-qty">
            <?= $escaper->escapeHtml(__('Qty')) ?>
        </th>
        <th class="item-price">
            <?= $escaper->escapeHtml(__('View')) ?>
        </th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td class="col product">
                <?= $escaper->escapeHtml($block->getWishlistItemName()) ?>
            </td>
            <td class="col">
                <?= $escaper->escapeHtml(__('getItemsSelection: %1', $block->getItemsSelection())) ?>
            </td>
            <td class="col">
                <a href="#" title="<?= $escaper->escapeHtml($block->getWishlistItemName()) ?>">
                    <?= $escaper->escapeHtml(__('View')) ?>
                </a>
            </td>
        </tr>
    </tbody>
</table>
