<?php
/**
 * Copyright (c) 2024 Attila Sagi
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/**
 * @var $block \Space\WishlistAdminEmail\Block\Wishlist\WishlistItems
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<table class="email-items">
    <thead>
    <tr>
        <th class="item-info"></th>
        <th class="item-info">
            <strong><?= $escaper->escapeHtml(__('Product Name')) ?></strong>
        </th>
        <th class="item-price">
            <strong><?= $escaper->escapeHtml(__('Price')) ?></strong>
        </th>
        <th class="item-qty">
            <strong><?= $escaper->escapeHtml(__('Qty')) ?></strong>
        </th>
        <th class="item-info"></th>
    </tr>
    </thead>
    <?php if ($block->getShowAllItems()) : ?>
        <tbody>
        <tr>
            <td class="item-info">
                <p>all items image</p>
            </td>
            <td class="item-info">
                <p>all items name</p>
            </td>
            <td class="item-price">
                <p>all items price</p>
            </td>
            <td class="item-qty">
                <p>all items qty</p>
            </td>
            <td class="item-info">
                <a href="#" title="#">
                    <?= $escaper->escapeHtml(__('View Product')) ?>
                </a>
            </td>
        </tr>
        </tbody>
    <?php else : ?>
        <?php $item = $block->getItem(); ?>
        <?php if (null !== $item) : ?>
            <?php $product = $block->getProduct(); ?>
            <tbody>
                <tr>
                    <td class="item-info">
                        <a href="<?= $escaper->escapeUrl($item->getProductUrl()) ?>">
                            <img src="<?= $escaper->escapeUrl($block->getImage($product)) ?>"
                                 alt="<?= $escaper->escapeHtml($product->getName()) ?>" />
                        </a>
                    </td>
                    <td class="item-info">
                        <a href="<?= $escaper->escapeUrl($item->getProductUrl()) ?>">
                            <p class="product-name"><?= $escaper->escapeHtml($product->getName()) ?></p>
                        </a>
                        <p class="sku">
                            <?= $escaper->escapeHtml(__('Sku')) ?>: <?= $escaper->escapeHtml($product->getSku()) ?>
                        </p>
                    </td>
                    <td class="item-price">
                        <?= $block->getProductPriceHtml($product) ?>
                    </td>
                    <td class="item-qty">
                        <?= $escaper->escapeHtml($item->getQty()) ?>
                    </td>
                    <td class="item-info">
                        <a href="<?= $escaper->escapeUrl($item->getProductUrl()) ?>"
                           title="<?= $escaper->escapeHtml($product->getName()) ?>">
                            <?= $escaper->escapeHtml(__('View Product')) ?>
                        </a>
                    </td>
                </tr>
            </tbody>
        <?php else : ?>
            <tbody>
                <tr>
                    <td class="item-info" colspan="5">
                        <p><?= $escaper->escapeHtml(__('Wishlist item not found.')) ?></p>
                    </td>
                </tr>
            </tbody>
        <?php endif; ?>
    <?php endif; ?>
</table>
